apache/couchdb-couch

- src/couch_file.erl
In the case when .delete directory contains lots of files.
The deletion of the directory leads to timeout in the supervisor.
Which in it's turn kills the node.
So we rename original directory so couchdb cannot find it.
Then we remove files from renamed directory asynchronously.
COUCHDB-2524
> Modify init_delete_dir to be async

- src/test_util.erl
Starting lager as `lager:start` is an issue since dependencies
started by lager are not included in a list of started applications
so we don't stop them after we are done with current test.
This commit uses test_util:start_applications so all deps of lager are
included into #test_context{}
COUCHDB-2688
> Include lager into list of extra apps when testing

- src/couch_db.erl
- src/couch_server.erl
Move duplicated logic into couch_db:normalize_dbname. We could use this
helper function anywhere we need to extract dbname from shard path.
COUCHDB-2715
We would need this PR for COUCHDB-2635
> Introduce couch_db:normalize_dbname

- src/couch_httpd_auth.erl
- src/couch_passwords.erl
- src/couch_users_db.erl
This gives the administrator control over which algorithm is used to
hash passwords and a separate control over whether this happens on
successful authentication or only at password change time.
closes COUCHDB-2725
> Configurable password scheme

- src/couch_db.erl
- src/couch_db_updater.erl
In `active_size` conversion in `couch_db:get_db_info/1` old db reduction's size format assumed to be an integer representing active state, when it also could be a tuple of active and external sizes.
This handeled correctly, for example, in [couch_db_updater.erl](https://github.com/apache/couchdb-couch/blob/master/src/couch_db_updater.erl#L426).
This patch addresses conversion of both possible formats to CouchDB `size_info` record.
This closes issue COUCHDB-2701
> Fix `active_size` format conversion in `get_db_info` function

- priv/couch_ejson_compare/couch_ejson_compare.c
MSVC uses __declspec(thread) rather than __thread, so created a macro for it.
> Support Windows compilation for couch_ejson_compare

- src/couch_httpd.erl
Revising original stance. Administrators can enable this feature if
they want, and supply the definitive list of allowed Host values.
When enabled, the default list of valid hosts is empty.
COUCHDB-2752
> Don't enable host validation by default

- src/couch_httpd.erl
- src/couch_httpd_csrf.erl
If the request parameter `csrf` is set to `true` when successfully
acquiring a session cookie from `_session` an additional cookie
(`Csrf-token`) is returned. All requests that send this new cookie
must also send a header (`X-Csrf-Token`) with the same value. If the
cookie is sent and the header is missing or different, a 403 response
is generated.
Note that the CSRF token is signed by the server so tampering is
detected and also results in a 403 response.
closes COUCHDB-2762
> Add CSRF protection

- src/couch_server.erl
- test/couch_server_tests.erl
Sometimes it is usefull to keep deleted db files around. For backup
reasons for example. This commit implements the feature. The feature is
enabled by specifying `rename_on_delete = true` in `[couchdb]` of the
config.
> Implement rename_on_delete

- src/couch_httpd_external.erl
A filtered call to _changes end-point prompts a node to
pull a peer from the received mochi request record.
This is crashing on the secondary nodes in a clustered
environment since the peer call made on a socket
that is not original for them.
The fix makes use of the fact that by the time of the request
the peer already got resolved on the coordinator node and
passed along as a part of #http record.
This closes the case COUCHDB-2785
> Fix crashing filtered _changes request

- src/couch_changes.erl
- src/couch_httpd_db.erl
- src/couch_httpd_misc_handlers.erl
validate that all POST requests with json body must have also have valid
json header: {"Content-Type": "application/json"}
This ensures a basic protection against CSRF
JIRA: COUCHDB-2775
> check POST requests for valid json header

- test/couchdb_os_daemons_tests.erl
couchdb_os_daemons_tests.erl was failing in
setup if run on its own:
```
... apps=couch tests=os_daemons_test_
```
with an exception:
```
**exit:{{{badmatch,undefined},
[{couch_log,notice,2,[{file,"src/couch_log.erl"},{line,44}]},
{config,handle_call,3,[{file,"src/config.erl"},{line,211}]},
```
because it depends on couch_log. So add couch_log as a dependency
in setup.
After fix it should run 5 tests:
```
[done in 5.626 s]
=======================================================
Failed: 0.  Skipped: 0.  Passed: 5.
```
COUCHDB-2830
> Fix couchdb_os_daemons tests dependency.

- test/couchdb_os_daemons_tests.erl
In isolation was failing in configuration_reader_test_
Because fixtures/os_daemon_configer.escript was
requesting uuids.algorithm from config application,
which was not set up.
COUCHDB-2831
> Fix OS Daemons test dependency.

- src/couch_stream.erl
`couch_stream` should be able to reuse the `io_priority` of whatever process creates it; it's then the creator's responsibility to decide what `io_priority` the stream should have.
Assigning streaming IO operations their own separately-tunable category of `io_priority` is an alternative to this change. The usefulness of that would depend on whether streaming IO in general has predictable load impacts that would be useful to observe and control for. Since `couch_stream` is only currently used by `couch_att`, though, giving attachment upload operations specifically an `io_priority` category might make more sense.
COUCHDB-2828
BugzID: 25815
> Inherit io_priority from the process creating the stream

- test/couch_db_tests.erl
I'm not sure what we testing here except our disk drives healthiness.
> Remove round for create/delete database for 1000 times

- priv/icu_driver/couch_icu_driver.c
It was caused by using ErlDrvSSizeT type instead of ErlDrvSizeT. It
was not an issue prior to R15 when ErlDrvSSizeT and ErlDrvSizeT where
basically int's.
Since we raised minimal Erlang release requirement up to R16B03-1,
there is no reason to maintain compatibility with pre-R15 for driver
so local COUCH_* types are replaced with ErlDrv* ones.
> Fix "initialization from incompatible pointer type" warning for icu drv

- src/couch_query_servers.erl
Due to how libmozjs185 library is compiled on Ubuntu 12.04, given
invalid JS code, it will not return with expected error result:
["error","compilation_error",...]
but will crash. Otherwise library seems functional --  it passes
all other mrview tests.
Handle this crash in try_compile() function as a compilation
failure. Error message contains the exit status of the view process
to help debugging.
> Handle view server crashing during test compile of view functions.

- test/couch_task_status_tests.erl
Previously, at the end of the test, it kills each status process
with call(Pid1, done), then immediately calls couch_task_status:all().
This caused a race between couch_task_status receiving the 'all'
call and the 'DOWN' message (from monitoring test processes). If
'DOWN' message came before 'all', test passed. If it came
after, it failed.
> Stabilize couch_task_status_tests:run_multiple_tasks/0 test.

- src/couch_sup.erl
lager, couch_log and friends starts long before couch_sup, so it seems safe to use couch_log instead of io:format here. Thoughts? @eiri @rnewson
> Use couch_log for startup notifications

- test/couch_work_queue_tests.erl
Failure seen at least once in about 150 test runs:
```
Queue with max size of 160 bytes and 3 max items
couch_work_queue_tests:143: should_have_no_items_for_new_queue...ok
**error:{assertEqual_failed,[{module,couch_work_queue_tests},
{line,210},
{expression,"couch_work_queue : item_count ( Q )"},
{expected,3},
{value,2}]}
```
From
```
should_block_producer_on_full_queue_count({Q, Producer, _}) ->
...
produce(Q, Producer, 20, false),
?assertEqual(3, couch_work_queue:item_count(Q)),
```
Race condition is: telling Producer to produce, not waiting
for queue size to be updated, and then immediately checking
item_count.
To make failure occur reliably insert timer:sleep(10) in
producer_loop after ```Parent ! {item, Ref, Item}``` line.
The fix is to wait for queue size to be updated by using
the …
> Fix race condition in workqueue test.

- src/couch_db.erl
This does two things:
- Fixes the way how user name is searched in list. lists:member/2 made in BIF, faster and doesn't causes redundant list copy;
- Fixes readers vs members terminology in code;
- Fixes COUCHDB-2534, throwing forbidden error if user is authenticated, but is not a database member.
> 2534 db security respect authed users

- src/couch_httpd.erl
Modern browsers (I tested Firefox, Safari, Chrome) will render an
application/json response body as text in a fixed width font. This
ease of display motivated the text/plain vs application/json
negotiation.
It is now obsolete. Let's always send application/json content type.
COUCHDB-2905
> Always send application/json response type

- src/test_util.erl
Also, create a common list of default apps that is started and stopped consistently
COUCHDB-2872
> Remove lager and goldrush from default list of apps started by test_util:start_couch/2

- src/couch_httpd_db.erl
Bring back 845bf7529a3bc565d6446a7fa6cc5fd1a140653e
The EventSource connection can get stuck (in TCP half-open state*) and there's no way
for the client to detect that. This commit changes the way heartbeat is sent, instead of
sending a newline character, it sends an empty event of type heartbeat:
event: heartbeat
data:
This event doesn't have an id: field, so the client will retain its latest Last-Event-ID state.
This doesn't change the expectations of clients that used EventSource till now, because they
subscribe to the 'message' event type. To get the 'heartbeat' events a client will need to
explicitly subscribe to it:
source.addEventListener('heartbeat', function () { /* cancel a timer that would otherwise reconnect the source */ });
* this can happen when you suspend your laptop, on …
> Send a real EventSource event for heartbeat

- src/couch_debug.erl
- src/couch_file.erl
Adding debugging function to list all opened couch_file files.
This function is for debugging purposes only. It iterates through all
open ports and returns file descriptor and filename correspondent to
every port.
> Add couch_file:open_files/0

- src/test_util.erl
- The order of arguments is incorrect.
- Return the result of stop_sync from with_process_restart/3
> Fix test_util:with_process_restart

- src/couch_changes.erl
- test/couch_changes_tests.erl
Not propagating the `delete` event to the changes callback causes
db to stay open when it is deleted in the presence of `continuous`
requests to `_changes` feed. This in its turn causes `couch_file` to stay
open until the connection is closed by the client.
> Propagate db delete event to changes callback

- src/couch_httpd.erl
Implement `before_response` and `before_serve_file` EPI hooks.
These hooks are useful in following cases:
- to inject vendor specific headers
- to inject vendor keys into json objects returned to client
- to override return code
This is a replacement PR for #133
> 2966 before response hook

- test/couch_db_plugin_tests.erl
The tests were over-wrapped. We should return simple tests from every test case. Otherwise the tests would always pass since `eunit` wouldn't execute the test body when `?_` used in this context.
> Fix incorrect use of eunit fixtures

- test/couchdb_views_tests.erl
There is a typo in one of the test suites.
This PR fixes it.
> Fix time:sleep -> timer:sleep typo

- test/couch_db_plugin_tests.erl
This fixes the problem with chttpd_plugin_tests. Previously following would fail:
```
make eunit apps=couch,chttpd tests=callback_test,error_info_test
```
In order to test this PR you would need to add apache/couchdb-erlang-tests#1 as a dependency in `rebar.config.script`. You might need to add the app into `rel/reltool.config` as well.
> Use couch_tests applications for couch_db_plugin_tests

- src/couch_db.erl
This uses the 64-bit IEEE format for floats, making the binary representation consistent between OTP versions before and after 17.0.
This also makes it easier for third parties to replicate the md5 portion of the revision id calculation.
> Use {minor_version, 1} on term_to_binary call for MD5 of _rev id

- src/couch_db_updater.erl
Prior to this commit, there was no functionality for a custom compactor
to know if the local database had been updated. This commit adds a
local_updated event, which will inform custom compactors when the local
tree has been updated.
> Add capability for compaction on local update

- src/couch_doc.erl
Signal mochiweb to not send connection:close headers
in order for the socket to be reused.
Before this commit, this signaling was done too late.
COUCHDB-2834
> When reading attachments, avoid closing connections too early

- priv/couch_js/utf8.c
We should undo our character advancement after we finish fixup.
COUCHDB-1425
> Undo our character advancement when we fixup

- src/couch_file.erl
- src/couch_server.erl
- test/couch_file_tests.erl
- test/couch_server_tests.erl
All the functions related to file deletion moved into `couch_file` module.
Config option `rename_on_delete` split into two options:
1. Option  `enable_database_recovery`. When set, on user initiated deletion of database renames a database file and the database's views directories in-place with timestamp and "deleted" tag-word suffix, so the database can be recovered if necessary.
2. Option `delete_after_rename`. When set, keeps all the deleted compaction files in ".delete" directory as renamed in random uuids files until the database restart. This allows to postpone deletion of the  compaction files and provides with option of "last minute safe" in case database got corrupted after compaction.
> Redo `enable_database_recovery` behaviour

- src/couch_compress.erl
- test/couch_compress_tests.erl
Right now when a binary without compression prefix passed on `couch_compress:decompress/1` (for example if a database file got corrupted), the module throws `function_clause` exception.
This patch adds tests for `couch_compress` module and makes `decompress/1` and `is_compressed/2` functions to raise `invalid_compression` error when they can't detect compression of passed binary.
> Raise better exception on decompress of corrupt binary

- src/couch_key_tree.erl
This is needed by fabric_doc_open_revs to fix COUCHDB-2863.
COUCHDB-2863
> Export couch_key_tree:merge/2

- src/couch_key_tree.erl
- test/couch_key_tree_tests.erl
This is a fix for a long standing bug when retrieving all leaf keys for
a given set of keys. Before this patch we would incorrectly return some
keys as missing if they happened to be deeper on a branch for a key that
was found if they weren't themselves a leaf key.
COUCHDB-2863
> Fix couch_key_tree:get_key_leafs/2

- priv/stats_descriptions.cfg
- src/couch_file.erl
- test/couch_file_tests.erl
When a database file goes corrupt it is possible that pread will receive bogus length and place a large part of the file in memory before couch_file process will crash. Depending on a size of the file this could bring the whole node down.
This change prevents pread from reading beyond end of a file and adding configuration parameter `max_pread_size` to give a method to address a situation when corrupted read does not go beyond eof, but still makes starting node crash on a large read.
Two stats counters been added to report both exceptions.
> Add config parameter to limit maximum pread size

- src/couch_server.erl
- test/couch_db_tests.erl
Pass `create_if_missing` option to be used in cases like these:
- [fabric_rpc:get_or_create_db/2](https://github.com/apache/couchdb-fabric/blob/master/src/fabric_rpc.erl#L270)
- [mem3_rpc:get_or_create_db/2](https://github.com/apache/couchdb-mem3/pull/21/files#diff-4d22d90c9d6ea299758d2f1262352379R278)
> Support create_if_missing option in couch_db:open

- test/couchdb_vhosts_tests.erl
In eunits the default security is "admin_local" and default security object for it was recently changed. This sets default_security for oauth tests to "everyone", allowing them to pass.
> Fix vhosts oauth tests

- src/couch_changes.erl
- test/couch_changes_tests.erl
A changes feed can be filtered using view's btree instead of a database btree, a feature known as `fast_view`. This feature not implemented on a clustered interface, however view filter automatically marked as `fast_view` when ddoc has option `seq_indexed` enabled, which leads to a crash of filtered replication.
This change allows `fast_view` filter to be processed as a regular view filter when used on a clustered
interface.
This is a temporary fix for 2.0 release made in consideration of feature freeze. It'll be revisited after the release after `fast_view` will be added into fabric.
COUCHDB-3044
> Fix changed feed view filter for clustered access

- test/couch_changes_tests.erl
In changes_tests, the changes feed consumer is a separate process that presumed to always run successfully and hence hides any abnormal exits, hiding it in `timeout` error. This making debugging of any failing tests rather complicated.
This changes makes consumer into monitored process and re-translates its exception to test suite in format common to eunit's assertion failures.
> Changes tests refactoring

- src/couch_httpd_auth.erl
Starting from 411c130ea63c3423d7ea71743095dfb446680da6 we accidentially
upgrading user's password to pbkdf.
Removing upgrade code.
> Remove maybe_upgrade_password_hash

- priv/couch_js/help.h
- priv/couch_js/main.c
- priv/couch_js/util.c
- priv/couch_js/util.h
This adds a class of test suite functions that are only available when a
command line switch is passed to couchjs. This so that the JavaScript
test suite has access to some helpful additional functions that aren't
part of the JavaScript language.
This particular change only adds a single `sleep` function which takes a
single argument as the number of milliseconds to sleep.
COUCHDB-3057
---
And a demonstration:
$ ./bin/couchjs -
sleep(5);
ReferenceError: sleep is not defined
Stacktrace:
@-:1
Failed to execute script.
$ ./bin/couchjs -T -
sleep(5000);
^D
davisp@cylinder master $ echo $?
0
> Add sleep as a test suite function

- .gitignore
- rebar.config
- test/couchdb_os_daemons_tests.erl
There are issues launching the .escript files automatically on Windows,
and the .sh files in the test will never run on Windows correctly. In the
interest of speeding along our release I'd like to simply skip these tests
on Windows for now. If launching a daemon completely fails we'll know
via the mrview tests.
Addresses COUCHDB-3040 but does not close it.
> Skip couchdb_os_daemons_tests on Windows

- src/couch_db.erl
- src/couch_db_plugin.erl
- test/couch_db_plugin_tests.erl
It is impossible to make the validation policy more tight from a plugin. This commit would let the plugin to do either tighten up or loosen the validation policy.  
COUCHDB-3066
> use couch epi decide

- src/couch_httpd.erl
Patch suggested by Ilya.
COUCHDB-3084
> Don't set "authenticated" if party_mode_handler sets user context

- src/couch_db.erl
Fix the case when DbName contains path to db file
In the case when DbName contains the file name we need to remove .couch
extension in order to match ?DBNAME_REGEX.
[COUCHDB-3080](https://issues.apache.org/jira/browse/COUCHDB-3080)
> fix validate dbname

- src/couch_proc_manager.erl
- src/couch_query_servers.erl
- test/couchdb_os_proc_pool.erl
This changes how proc manager handles proc assignment. Instead of doing this in three different places: `get_proc` call handler, `return_proc/2` with `maybe_assign_proc` and `flush_waiters/2`, proc manager now just places all the incoming requests in the waiting queue and then flushes it. 
As a result all the logic kept in one place which makes it more obvious that we are treating proc management as a processing of a single FIFO queue with "soft" and "hard" upper limits.
Consequently this is fixing a bug in `maybe_assign_proc` where it was possible to assign a client a process that wasn't aware of it.
COUCHDB-3095
> Simplify proc manager by moving assignment logic in one place

- src/couch_doc.erl
- test/couch_doc_tests.erl
Because binary match treats end of binary as `<<>>` we are validating "_design/" and "_local/" as proper ids.
COUCHDB-3114
> Fix validation for ddoc and _local id

- test/couchdb_os_proc_pool.erl
COUCHDB-3140
This PR disables the problematic queue-as-fifo test. As written, any
call in a test to spawn_client/1 returns immediately, and does not
guarantee that the call to couch_query_servers:get_ddoc_process/2
returns before control flow proceeds to the next line in the eunit test.
As it turns out, on Windows, the call to spawn_client for ddoc5 succeeds
prior to the ddoc4 call in this test, thus always failing.
Insertion of a timer:sleep/1 call between the spawn_client/1 calls seems
to solve the problem, but even this is "lucky" behaviour. Semantically
the way this test is written, with spawn_client/1 using spawn/1 to spin
off the actual get_ddoc_process/2 call, there is no guarantee that the
couch_proc_manager FIFO queue is being populated correctly.
Further, if the …
> Disable should_process_waiting_queue_as_fifo test

- rebar.config.script
- src/couch.app.src.script
For some reason, the COUCHDB_VERSION string on Windows is getting
suffixed whitespace. We fix this by string:strip(Version0, right) on the
variable before use.
> Fix Windows version string determination

- rebar.config
- rebar.config.script
- src/couch.app.src
- src/couch.app.src.script
- src/couch_server.erl
This changes the way we set the value for `couch_server:get_version`. The `get_version` function is used in:
- version key of welcome message
- Server header returned in every response
This implementation defines a COUCH_VERSION macro. This is done in order to ensure that we keep using `{vsn, git},` in `src/couch.app.src`. There is also additional benefit of using the macro. It saves us an access to ets table. ETS is used for `application:get_key`. Since get_version is called for every request the saving should be significant. This would improve on previous analysis and work done by @robertkowalski [here](https://github.com/robertkowalski/kowalski.gd/blob/master/_posts/2016-02-10-high-performance-erlang-finding-bottlenecks-couchdb-1.md).
> Define couch version

- priv/couch_js/utf8.c
This was a bad backport from an old bug. We accidentally backed up when
looking at the second half of a surrogate pair. Instead the backup
should only happen when we see a low half of a surrogate pair with no
preceding high half.
COUCHDB-3173
> Fix CouchJS character replacement

- src/couch_httpd.erl
- src/couch_httpd_db.erl
Previously multipart/related PUT requests didn't check maximum request sizes.
This commit checks content-length and compares that with the maximum.
This means keeping the current "semantics" of max_document_size which actually
means "max request size". But this makes the check more efficient and can
be done earlier in request processing time.
Jira: COUCHDB-3174
> Add max_document_size checking for multipart PUT requests

- src/couch_debug.erl
couch_debug:opened_files_by_regexp is an efficient way to find out list
of file descriptors or couch_file processes which path matches given
regexp
> Add couch_debug:opened_files_by_regexp/1

- src/couch_file.erl
- test/couch_file_tests.erl
Add PathFile as part of a reason for following errors:
- read_beyond_eof
- exceed_pread_limit exceptions
> Include file_path on errors from couch_file

- src/couch_db.erl
- test/couch_db_doc_tests.erl
This PR drags unrelated commits because the sync between ASF and github is currently broken.
> truncate revs to revs limit

- include/couch_js_functions.hrl
- test/couch_auth_cache_tests.erl
Allow adding missing fields:
- type
- roles
Allow update of the type field from incorrect value to the correct one
(currently it suppose to have value 'user').
COUCHDB-3231
> Allow fixing users' documents

- priv/couch_js/main.c
Previously it was used to set JS context's stack chunk size.
Instead, to be effective it should set max GC size of the runtime.
Stack chunk size was set to the recommended value: 8K
Reference:
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey/JSAPI_reference/JS_NewContext
COUCHDB-3245
> Make couchjs -S option take effect

- src/couch_db.erl
- src/couch_server.erl
- src/couch_util.erl
It turns out that filename:rootname/1 is fairly expensive. Given that we
call it millions of times when doing database name validation it adds up
significantly. This is a fairly easy optimization to just use binary
matching instead.
COUCHDB-3251
> Remove use of filename:rootname/1

- test/couch_changes_tests.erl
This adds tests for basic filtering of _changes feed by "filters" function both for filtering by doc attributes and by passed in request object. This is complimentary to apache/couchdb-chttpd#150
The test also was refactored to reduce code duplication and name variables consistently.
COUCHDB-3233
> Add test for filter _changes by filters function

- src/couch_db.erl
- test/couch_db_mpr_tests.erl
This removes the influence of the attachment disk information when
generating revisions when a document is being recreated (ie, it existed
once but has been deleted).
COUCHDB-3255
> Make revision generation deterministic

- test/couchdb_views_tests.erl
Previous commit made couch_file to monitor db_pid instead of linking to it, so number of `monitored_by` for couch_db process, checked in `couchdb_views_tests`, changed.
COUCHDB-3259
> Fix couchdb_views tests

- src/couch_httpd_misc_handlers.erl
Added validation on "count" parameter to be positive and changed return code for "count" exceeding maximum from "Forbidden" to "Bad Request"
COUCHDB-3273
> Improve errors on invalid "count" parameter in /_uuids

- src/couch_file.erl
We can't know if one or more bytes were written by a file:write/2 call
that results in an error and so it is not correct to leave #file.eof
at its original value. In the event of error, use file:position(Fd,
eof) to find the new, true length of the file, and update #file{}
accordingly.
COUCHDB-3274
> Reset EOF if a partial write was possible

- src/couch_query_servers.erl
Validation function can throw JSON with error type different than forbidden or unauthorized.
This patch makes couch return unknown_error instead of crashing query server.
COUCHDB-3286
> Don't crash on unexpected validation's error type

- src/couch_file.erl
This code was left over after removing 8kB read-ahead
https://github.com/apache/couchdb-couch/pull/223/commits/d52a5335d930d11ade4953c8576d22f55872ff6f
COUCHDB-3284
> Remove dead code from couch_file

- src/test_request.erl
Sometimes it is useful to be able to pass headers in test case to a delete request. 
Adding delete/3 to be able to do so.
> Add test_request:delete/3

- src/couch_doc.erl
- test/couch_doc_json_tests.erl
- test/couch_doc_tests.erl
Previously it was not possibly to define a maxum document ID size. That meant
large document ID would hit various limitations and corner cases. For example,
large document IDs could be inserted via a _bulk_docs endpoint but then trying
to insert the same document via a single HTTP method like PUT would fail
because of a limitation in Mochiweb's HTTP parser.
Let operators specify a maxium document ID length via the:
```
couchdb.max_document_id_length = infinity | Integer```
configuration.
The default value of `infinity` means current behavior where document ID length is not
checked.
COUCHDB-3293
> Allow limiting length of document ID

- src/couch_db.erl
When folding we account for a previous `null`, `undefined`, or a number. However
btree:size/1 returns 0, `nil` or a number.
Switched `undefined` to `nil`. Couldn't find where btree:size would ever return
`undefined`, it seems we meant to use `nil` instead.
COUCHDB-3316
> Fix `badarith` error in couch_db:get_db_info call

- src/couch_httpd.erl
- src/couch_httpd_external.erl
`max_document_size` is implemented as `max_http_request_size`. There was no
real check for document size. In some cases the implementation was close enough
of a proxy (PUT-ing and GET-ing single docs), but in some edge cases, like
_bulk_docs requests the discrepancy between request size and document size
could be rather large.
The section was changed accordingly from `couchdb` to `httpd`. `httpd` was
chosen as it applies to both clustered as well as local interface.
There is a parallel effort to implement an actual max_document_size check. The
set of commit should be merged close enough together to allow for a backwards
compatible transition.
COUCHDB-2992
> Rename max_document_size to max_http_request_size

- src/couch_query_servers.erl
This a fixup for https://github.com/apache/couchdb-couch/pull/229.
The initial value for accumulator suppose to be 0. Since the result of
sum and count is integer. The problem was discovered by dialyzer.
COUCHDB-3305
> Fix initial accumulator value for builtin_sum_rows

- src/couch_db_updater.erl
- src/couch_file.erl
- src/couch_lru.erl
- src/couch_server.erl
- test/couchdb_views_tests.erl
_replicator and _users db's have been excluded from the LRU for a long time. This is fine when you have one of each, it's not fine when you have tens of thousands of each.
Note: I've intentionally changed max_dbs_open to be a soft limit rather than a hard one. couchdb's behavior when it throws all_dbs_active is pretty poor (you can create a database that you can't open later, for example) so I think it better to remove that class of problems.
COUCHDB-3325
> Add sys_dbs to the LRU
