src/couch_auth_cache.erl, src/couch_compaction_daemon.erl, src/couch_drv.erl, src/couch_external_manager.erl, src/couch_external_server.erl, src/couch_httpd.erl, src/couch_httpd_auth.erl, src/couch_httpd_misc_handlers.erl, src/couch_httpd_vhost.erl, src/couch_os_daemons.erl, src/couch_proc_manager.erl, src/couch_server.erl, src/couch_sup.erl, src/couch_uuids.erl, test/couchdb_attachments_tests.erl
This PR should go with https://github.com/apache/couchdb-config/pull/2
=> 2561 make config api consistent

include/couch_db.hrl, src/couch_server.erl
Includes:
https://github.com/apache/couchdb/pull/306
https://github.com/apache/couchdb-chttpd/pull/27
https://github.com/apache/couchdb-cassim/pull/3
https://github.com/apache/couchdb-mem3/pull/6
https://github.com/apache/couchdb-fabric/pull/15
https://github.com/apache/couchdb-setup/pull/1
=> Rename system databases

src/couch_util.erl, test/couch_util_tests.erl
=> Add couch_util:validate_callback_exists

test/couchdb_mrview_cors_tests.erl
=> Add CORS test case for couch_mrview_show

src/couch_httpd_misc_handlers.erl
=> Week of day for past expiration date 1990-01-01 is Monday

test/couchdb_mrview_cors_tests.erl
=> Fix broken test suite for COUCHDB-2656

test/global_changes_tests.erl
=> Add test suite for global_changes

src/test_request.erl
We need to pass auth in Opts sometimes.
COUCHDB-2689
=> Pass Opts to put/post/delete of test_request

src/couch_changes.erl
JIRA: COUCHDB-2743
BugzID: 48864
=> Throw bad request for empty POST request body when filtering by doc_ids

priv/couch_ejson_compare/couch_ejson_compare.c
The old nif was allocating a set of collators that were reserved and
released by each scheduler thread. This coordination and the
accompanying mutex turned into a global point of contention when many
schedulers were using couch_ejson_compare.
This change removes the stack based concurrency control in favor of a
`__thread variable`. We end up with the same number of collators but
without any overhead around locking a central mutex.
This increases performance by roughly a factor of five.
COUCHDB-2732
=> Optimize couch_ejson_compare NIF

src/couch_httpd.erl
By default, the Host header must be either localhost or the
fully-qualified domain name of the host.
Administrators can disable this check with;
[httpd]
validate_host = false
Administrators can override the valid host list with;
[httpd]
valid_hosts = foo,bar,baz
COUCHDB-2752
=> Validate host header

src/couch_httpd_csrf.erl
When enabled, the CSRF cookie/header is required on all requests
except those to the welcome message at /.
COUCHDB-2762
=> Add option to make CSRF cookie mandatory

src/couch_httpd_csrf.erl
=> CSRF is not necessary for read operations

src/couch_httpd_auth.erl
=> Log when password is wrong but user is valid

src/couch_httpd.erl
This also removes need in special wrapper to handle atom as default
for config:get call.
COUCHDB-2783
=> Bind both to IPv4 and IPv6 with special "any" value

priv/stats_descriptions.cfg, src/couch_httpd_db.erl
=> Capture histogram data for _bulk_requests

src/couch_db_plugin.erl, src/couch_secondary_sup.erl
This PR depends on https://github.com/apache/couchdb-couch-epi/pull/8
=> 2796 improve performance of providers function

src/couch_httpd_csrf.erl
=> Restrict CSRF check to specific mime types

src/couch_db.erl
=> Convert compilation error to 400 Bad Request

src/couch_httpd.erl
=> Use lists:ukeymerge to simplify header deduplication

src/couch_crypto.erl, src/couch_db.erl, src/couch_db_updater.erl, src/couch_file.erl, src/couch_hotp.erl, src/couch_httpd.erl, src/couch_httpd_auth.erl, src/couch_native_process.erl, src/couch_passwords.erl, src/couch_server.erl, src/couch_stream.erl, src/couch_util.erl, test/couch_auth_cache_tests.erl, test/couchdb_attachments_tests.erl
=> Fix crypto deprecations

test/couch_task_status_tests.erl
It depends on couch_log to be running. Otherwise it
throw this error:
```
unexpected termination of test process*
::{{badmatch,undefined},
[{couch_log,debug,2,[{file,"src/couch_log.erl"},{line,32}]},
{couch_task_status,handle_cast,2,
[{file,"src/couch_task_status.erl"},{line,137}]},
```
And only 6 out of 11 tests are run.
COUCHDB-2832
=> Fix task status unit test dependency

src/couch_db_epi.erl, src/couch_secondary_sup.erl, src/test_util.erl, test/couch_db_plugin_tests.erl
Depends on https://github.com/apache/couchdb-couch-epi/pull/12
=> Update to new couch_epi API

src/couch_server.erl, test/couch_server_tests.erl
In order to support `rename_on_delete` semantics for views. We want to reuse `couch_server:delete_file` in couch_mrview_cleanup.
=> Export delete file

src/couch_doc.erl
=> Throw if parse_revs is not a list

test/couchdb_views_tests.erl
* Give couchdb_1283 tests more docs to process so compactor
stays running longer.
* In couchdb_1309, when waiting for view cleanup, test once,
if fails due to race condition, wait a second and try again.
COUCHDB-2848
=> Increase EUnit views tests stability

test/couchdb_os_daemons_tests.erl
Increase delay timeout to fix this failure:
```
**error:{assertNotEqual,[{module,couchdb_os_daemons_tests},
{line,207},
{expression,"D # daemon . kill"},
{value,undefined}]}
```
So far noticed this failure once out of more than 100 runs.
=> Stabilize os daemons test

test/couch_db_plugin_tests.erl
Save current couch_epi application environment plugins in context during test setup, and restore during teardown.
COUCHDB-2868
=> Run tests with only the couch_db_plugin_test couch_epi plugin

test/couchdb_mrview_cors_tests.erl
Create admin user and use its credentials for requests
Use http requests to create and delete test dbs to avoid potential db
name munging issues downstream
COUCHDB-2897
=> Explicitly authorize test requests

src/couch_native_process.erl, src/couch_query_servers.erl
=> Rewrite via query server

src/couch_server.erl
=> Remove configurable replicator db name

src/couch_changes.erl
This extends a change introduced in PR #134 to be used with filtered by view replication.
=> Extend fetch ddoc logic for view filtered changes feeds

src/couch_httpd.erl
After recent refactoring `log_response/2` can also receive an unencoded JSON as part of the error message.
=> Fix log_response/2

src/couch_db.erl
We shouldn't rely on dbname being the last part of path. Since database
name could include slashes.
normalize_dbname as the name suggests should accept either binary or
list and return only binary.
=> Fix normalize_dbname to work with slashes

src/couch_changes.erl, test/couch_changes_tests.erl
API is modeled after _doc_ids filter for change feeds.
User POSTs to {db}/_changes with `filter=_selector`.
Document body should have a "selector" field, with
a Mango selector object as value.
For example:
```
http://.../d1/_changes?filter=_selector
{
"selector": {"z" : {"$gte" : 1} }
}
```
In case "selector" is missing or its value is not a
JSON object, a 400 error is returned with a
corresponding error message. For example:
```
{
"error": "bad_request",
"reason": "Selector error: 42, expected an object"
}
```
In case "selector" object cannot be validated as a
Mango selector, a 400 error is returned with a validation
error as "reason".
Jira: COUCHDB-2988
=> Implement Mango selectors for change feeds

src/couch_db.erl
normalize_dbname used to return last componenent of the shard path. But
it was doing so only if argument was passed as a binary. We change the
semantic of normalize_dbname so it does following:
1. expects either type binary or list
2. expect any kind of database name
- plain database name
- plain database name with '.couch' extension
- shard name with suffix (creation time)
- shard name with suffix (creation time) and .couch extension
3. always returns a binary containing all components of a database name
4. removes information about shard
5. removes shard's suffix
For cases we need last component of the path (old behaviour) we
intoroduce dbname_suffix/1
COUCHDB-2983
=> Change normalize_dbname semantic add dbname_suffix

src/couch_os_process.erl
=> Use ioq to separately prioritise prompt requests

src/couch_db_updater.erl
=> Allow customisation of default security object

src/couch_db_updater.erl
=> Add admin_local - halfway between the two schemes

src/couch_auth_cache.erl, src/couch_event_sup.erl, src/couch_file.erl, src/couch_proc_manager.erl
Update couple of type specs.
Fix couple of real bugs in:
- `couch_event_sup`
- `couch_proc_manager`
=> Fix some type errors

test/couchdb_design_doc_tests.erl
It is a PR containing test suite for https://github.com/apache/couchdb-couch-mrview/pull/49
COUCHDB-2847
=> Add test suite for _list functionality

src/couch_changes.erl, src/couch_key_tree.erl, src/couch_proc_manager.erl
Fixing some of the dialyzer warnings
=> Fix some specs

src/couch_auth_cache.erl, src/couch_compaction_daemon.erl, src/couch_external_manager.erl, src/couch_external_server.erl, src/couch_httpd_vhost.erl, src/couch_os_daemons.erl, src/couch_proc_manager.erl, src/couch_server.erl, src/couch_sup.erl, src/couch_uuids.erl
Update handle_config_terminate API to match changes in https://github.com/apache/couchdb-config/pull/11
COUCHDB-3102
=> Update handle_config_terminate API

src/couch_server.erl
Fixes the case when the following are configured to something other than _users
- chttpd_auth.authentication_db
- couch_httpd_auth.authentication_db
Introduce "couchdb.users_db_suffix" config key
Remove distinction between clustered and local users databases
configuration. We remove following configuration options and replace
them with "couchdb.users_db_suffix":
- chttpd_auth.authentication_db
- couch_httpd_auth.authentication_db
COUCHDB-2731
=> Make sure authentication_db for clustered is considered as users db

src/couch_file.erl
The current find_header algorithm performs one file read per block,
which can be inefficient when the most recent header is buried deeply in
a large file.
With default config params, this change essentially keeps current
behavior, reading each block into memory one at a time until a header is
found, or beginning of file is reached. However, by setting new config
params, it's possible to exponentially increase the number of blocks
read into a "chunk" of memory with a single read, up to a configurable
limit.
For example, the following settings begin with a chunk size of one
block, and then double in size each additional search step backward to a
maximum limit of 16GB:
[couchdb]
chunk_max_size = 4096*4096
chunk_exponent_base = 2
Measurements for a 12GB .couch.meta file with its last header …
=> 3061 adaptive header search

test/couchdb_mrview_tests.erl
Test suite for https://github.com/apache/couchdb-chttpd/pull/140
COUCHDB-3158
=> Adding test suite for trancated _update

test/couchdb_file_compression_tests.erl
=> Replace `stale` with `update` in compression tests

src/couch_changes.erl, test/couch_changes_tests.erl
(This could be postponed until after 2.0 release. Issued to get comments and review).
When using selectors with `include_docs=true` can specify an optional fields
array in the POST request JSON body.
Each element in the array can be a json field (or even a key path
specified as field1.field2...). Resulting documents will contain only the
specified document fields.
For example:
```
http://.../d1/_changes?filter=_selector&include_docs=true
{
"selector": {"z" : {"$gte" : 1} }, "fields": ["field1", "field2"]
}
```
Will first select only document with "z" value >= 1, then will return only field1 and field2 in documents.
`{ "field1": "field1value", "field2": "field2value"}`
(This requires a companion pr in fabric to work)
Jira: COUCHDB-2988
=> Add optional `fields` to change feed selectors

test/couchdb_mrview_tests.erl
Test suite for https://github.com/apache/couchdb-chttpd/pull/146
=> handle errors terms from fabric

src/couch_server.erl
Opening a database is asynchronous, therefore it's possible for the
database to have been deleted before the open is complete. The
open_result code assumes this doesn't happen, so when it does,
couch_server crashes, taking the couch_dbs ETS table with it.
Explicitly handle the case and keep on keeping on.
COUCHDB-3241
=> Handle open_result message that arrives after the delete

src/couch_file.erl
It turns out to be impossible to trap the exit message from the parent
process in a gen_server, which is the only reason couch_file traps
exits in the first place (i.e, this has never worked).
This commit also changes the hot upgrade code to handle this
transition (but not the previous one).
COUCHDB-3259
=> Don't trap exits in couch_file

src/couch_file.erl
In production it showed an increased input Erlang IO and increased binary
memory usage.
See attached file in Jira ticket:
COUCHDB-3284
=> Remove 8kB read-ahead from couch_file

src/couch_server.erl
Currently we are adding the sys db callbacks for every request instead once
while opening the db. This fix will ensure that we will only add the sys
db calls backs once while opening the db.
COUCHDB-3307
=> Add sys db callbacks only once per db open

src/couch_httpd_vhost.erl
=> Efficiently bypass vhost handling if there are none

src/couch_query_servers.erl
When input is invalid for built in reducers, we return an error row
instead of crashing.  Thanks to @davisp for providing the elegant
solution.
The results now look like this:
```
{
"rows": [
{
"key": null,
"value": {
"key": [],
"value": [
{
"a": 1
},
{
"a": 2
},
{
"a": 3
},
{
"a": 4
}
],
"builtin_reduce_error": "The _sum function requires that map values be numbers, arrays of numbers, or objects, not '[{[{<<\"b\">>,\n                                                                                               1}]},\n                                                                                            {[{<<\"b\">>,\n                                                                                               2}]},\n …
```
=> Return error row instead of crashing

src/couch_lru.erl, test/couch_lru_tests.erl
The interface is the same as previous couch_lru.
=> An ETS based couch_lru
